services:
  postgres:
    image: 'postgres:16'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      - '.:/app'
    environment:
      POSTGRES_PASSWORD: password123
  
  website:
    depends_on:
      - postgres
      - solr
    environment:
      MAILER_DELIVERY_METHOD: smtp
      SMTP_ADDRESS: localhost
      SMTP_PORT: 25
      SMTP_USERNAME: ''
      SMTP_PASSWORD: ''
    build: .
    ports:
      - '3000:3000'
      - '1080:1080'
    volumes:
      - '.:/app'

  solr:
    image: solr:latest
    ports:
      - '8983:8983'
    volumes:
      - solr:/opt/solr/server/solr
      - ./config/solr/schema.xml:/opt/solr/server/solr/configsets/_default/conf/schema.xml
      - ./config/solr/solrconfig.xml:/opt/solr/server/solr/configsets/_default/conf/solrconfig.xml
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - production
    restart: unless-stopped

volumes:
  postgres:
  solr:
