defaults: &DEFAULTS
    default_edition: "The Poems of Emily Dickinson: Variorum Edition"
    placeholder_image_url: "http://www.archives.gov/exhibits/featured_documents/henry_o_flipper/images/letter_page_02.jpg"

development:
    <<: *DEFAULTS
    image_host: "http://localhost/iipsrv/iipsrv.fcgi"
    image_directory: "/home/justin/Desktop/images/output/zoomable"
    web_image_directory: "previews/"
    data_directory: "/home/justin/projects/emily/app/data"

test:
    <<: *DEFAULTS
    image_host: "http://interop.lib.harvard.edu:9080/cgi-bin/iipsrv.fcgi"
    image_directory: "/home/iip/dev/images/tiff"
    web_image_directory: "previews_test"

production:
    <<: *DEFAULTS
