defaults: &DEFAULTS
    default_edition: "The Poems of Emily Dickinson: Variorum Edition"
    placeholder_image_url: "http://www.archives.gov/exhibits/featured_documents/henry_o_flipper/images/letter_page_02.jpg"

development:
    <<: *DEFAULTS
    image_host: "http://localhost/iipsrv/iipsrv.fcgi"
    image_directory: "/mnt/hgfs/eda_images/output/zoomable"
    web_image_directory: "previews/"
    data_directory: "eda_data"

test:
    <<: *DEFAULTS

production:
    <<: *DEFAULTS
